app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='home'),
    

    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
    path('add-to-cart/<id>', views.add_to_cart, name="add"),
    path('add-to-cart-detail/<id>', views.add_to_cart_detail, name="add-detail"),

    path('remove-from-cart/<id>', views.remove_from_cart, name="remove"),
    path('product/<id>', views.detail_view, name="detail"),
    path('item-occasions', views.occasions_list, name="occasions"),
    path("customize-your-box", views.chocolate_type, name="chocolate_type"),
    # path("customize-your-box/chocolate-weight", views.chocolate_weight, name="chocolate_weight"),
    # path("customize-your-box/chocolate-box", views.chocolate_box, name="chocolate_box"),
    # path("customize-your-box/box-items", views.box_items_choice, name="box-items-choice"),
    path("customize-your-box/box-items-post", views.box_items_choice_post, name="box-items-choice-post"),
    # path('customize-your-box/done', views.custom_box_done, name="box-done"),
    path('cart', views.cart, name="cart"),
    path('add-quantity/<slug>', views.add_quantity, name="add-quantity"),
    path('remove-quantity/<id>', views.remove_quantity, name="remove-quantity"),
    path('checkout', views.CheckoutView.as_view(), name='checkout'),
    path('checkout-post', views.checkout, name='checkout-post'),
    path('clear-cart', views.clear_cart, name="clear-cart"),
    path('account/<pk>', views.Account.as_view(), name="account"),
    path('about-us', views.about_us, name="about-us"),
    path("ajax-add/<id>", views.ajax_add, name="ajax-add"),
    path("add-box-quantity/<slug>", views.add_box_quantity, name="add-box-quantity"),
    path("remove-box-quantity/<id>", views.remove_box_quantity, name="remove-box-quantity"),
    path("remove-box-from-cart/<id>", views.remove_box_from_cart, name="remove-box-from-cart"),
    path("add-checkout/<id>", views.add_check, name="add-check"),
    path("remove-checkout/<slug>", views.remove_check, name="remove-check"),
    path("add-box-checkout/<slug>", views.add_box_quantity_check, name="add-box-check"),
    path("remove-box-checkout/<slug>", views.remove_box_check, name="remove-box-check"),
    path("operation", views.operation, name="op-index"),
    path("operation/login", views.operation_login, name="op-login"),
    path("operation/order_details/<id>", views.order_details, name="op-order-details"),
    path("socket-checkout", views.socket_checkout, name="socket-checkout"),
    path("checkout-done", views.checkout_done, name="checkout-done"),
    path("verify-email", views.email_verification, name="check-pin"),
    path("send-payment", views.send_payment, name="send-payment"),
    path("ar-send-payment", views.ar_send_payment, name="ar-send-payment"),

    path("add-favorite/<id>", views.add_favorite, name="add-favorite"),
    path("remove-favorite/<id>", views.remove_favorite, name="remove-favorite"),
    path("add-favorite-detail/<id>", views.add_favorite_detail, name="add-favorite-detail"),
    path("remove-favorite-detail/<id>", views.remove_favorite_detail, name="remove-favorite-detail"),
    path("search-results", views.search, name="search"),
    path("favorites", views.favorites, name="favorites"),
    path("category-items/<id>", views.categories_home, name="category-items"),
    path("forgot-password", views.forgot_password, name="forgot-password"),
    path("reset-password", views.reset_password, name="reset-password"),
    path("change-password", views.change_password, name="change-password"),
    path("orders-history", views.orders_history, name="orders-history"),
    path("visitor", views.visitor, name="visitor"),
    path("terms-conditions", views.terms_and_conditions, name="terms-conditions"),
    path("privacy-policy", views.privacy_policy, name="privacy-policy"),
    path("add-visits", views.add_visits, name="add-visits"),
    path("checkout-failed", views.checkout_failed, name="checkout-failed"),


    path("submit-coupon", views.submit_coupon, name="submit-coupon"),
    path("replace-coupon", views.replace_coupon, name="replace-coupon"),


    path("ar-submit-coupon", views.ar_submit_coupon, name="ar-submit-coupon"),
    path("ar-replace-coupon", views.ar_replace_coupon, name="ar-replace-coupon"),






    path("create-visitor", views.create_visitor, name="create-visitor"),

    path("order-summary", views.order_summary, name="order-summary"),



    path("subscribe", views.subscribe, name="subscribe"),
    path("contact-us", views.contact_us_post, name="contact-us"),


    



    path("send-conf-email", views.send_confirmatiion_email),

    




    







    path('ar/', views.ar_index, name='ar-home'),
    path('ar/category-items/<id>', views.ar_categories_home, name='ar-category-items'),
    path('ar/product/<id>', views.ar_detail_view, name='ar-detail'),
    path("ar/customize-your-box", views.ar_chocolate_type, name="ar_chocolate_type"),
    path("ar/about-us", views.ar_about_us, name="ar-about-us"),
    path("ar/register", views.ar_register, name="ar-register"),
    path("ar/login", views.ar_user_login, name="ar-login"),
    path("ar/logout", views.ar_user_logout, name="ar-logout"),
    path("ar/cart", views.ar_cart, name="ar-cart"),
    path('ar/checkout', views.ArCheckoutView.as_view(), name='ar-checkout'),
    path('ar/account/<pk>', views.ArAccount.as_view(), name='ar-account'),
    path('ar/change-password', views.ar_change_password, name='ar-change-password'),
    path('ar/reset-password', views.ar_reset_password, name='ar-reset-password'),
    path('ar/forgot-password', views.ar_forgot_password, name='ar-forgot-password'),


    path('ar/orders-history', views.ar_orders_history, name='ar-orders-history'),
    path('ar/favorites', views.ar_favorites, name='ar-favorites'),
    path("ar/search-results", views.ar_search, name="ar-search"),
    path('ar/checkout-post', views.ar_checkout, name='ar-checkout-post'),
    path("ar/visitor", views.ar_visitor, name="ar-visitor"),
    path("ar/checkout-done", views.ar_checkout_done, name="ar-checkout-done"),
    path("ar/socket-checkout", views.ar_socket_checkout, name="ar-socket-checkout"),
    path("ar/terms-conditions", views.ar_terms_and_conditions, name="ar-terms-conditions"),
    path("ar/order-summary", views.ar_order_summary, name="ar-order-summary"),
    path("ar/privacy-policy", views.ar_privacy_policy, name="ar-privacy-policy"),
    path("ar-remove-box-from-cart/<id>", views.ar_remove_box_from_cart, name="ar-remove-box-from-cart"),
    path("ar/verify-email", views.ar_email_verification, name="ar-check-pin"),
    path("ar/checkout-failed", views.ar_checkout_failed, name="ar-checkout-failed"),
    path("ar/create-visitor", views.ar_create_visitor, name="ar-create-visitor"),




    path("images", views.images)














    
    










]


# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chocolate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path("dashboard/", include("dashboard.urls")),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from email.policy import default
from django.core.mail import mail_admins
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import SET_NULL
from django.db.models.expressions import Case
from django.db.models.fields import BLANK_CHOICE_DASH, IntegerField
from django.db.models.fields import related
from django.db.models.fields.related import ForeignKey
from django.utils import timezone
from cloudinary.models import CloudinaryField
from django.urls import reverse
from django.utils.text import slugify
import datetime
from django.dispatch import receiver
import cloudinary
import cloudinary.uploader
import decimal


from . import validators




CHOCOLATE_TYPE = (
    ("Bars", "Bars"),
    ("Pralines", "Pralines"),
    ("Dragers", "Dragers"),
    ("Belgium Truffles", "Belgium Truffles"),

)


TRAY_CHOCOLATE_TYPE = (
    ("Bars", "Bars"),
    ("Pralines", "Pralines"),
    ("Dragers", "Dragers"),
    ("Bars and Pralines", "Bars and Pralines"),
    ("Bars and Dragers", "Bars and Dragers"),
    ("Belgium Truffles", "Belgium Truffles")
)

QUANTITY_CHOICE = (
    ("Kilogram", "Kilogram"),
    ("Half Kilo", "Half Kilo"),
    ("Quarter Kilo", "Quarter Kilo")
)

UNIT_CHOICE = (
    ("Kilogram", "Kilogram"),
    ("Gram", "Gram"),
)


AR_UNIT_CHOICE = (
    ("كجم", "كجم"),
    ("جرام", "جرام"),
)


BOX_IMAGE_CHOICE = (
    ("box_1.png", "box_1.png"),
    ("box_2.png", "box_2.png"),
    ("box_3.png", "box_3.png"),
)



ORDER_STATUS = (
    ("Received", "Received"),
    ("Processing", "Processing"),
    ("On Delivery", "On Delivery"),
    ("Delivered", "Delivered"),

)



EN_DELIVERY_DATES = (
    ("Same Day", "0"),
    ("1 Day", "1 Day"),
    ("2 Days", "2 Days"),
    ("3 Day", "3 Day"),

)



AR_DELIVERY_DATES = (
    ("نفس اليوم", "نفس اليوم"),
    ("بعد يوم", "بعد يوم"),
    ("بعد يومين", "بعد يومين"),
    ("بعد ٣ ايام", "بعد ٣ ايام"),

)

QUANTITY_TYPES = (
    ("Weight", "Weight"),
    ("Pieces", "Pieces"),

)

User._meta.get_field("email").blank = False
User._meta.get_field("email").null = False






class Flavor(models.Model):
    en_name = models.CharField(max_length=100)
    ar_name = models.CharField(max_length=100)
    index = models.IntegerField(default=1)



    def __str__(self):
        return self.en_name


class Color(models.Model):
    en_name = models.CharField(max_length=100)
    ar_name = models.CharField(max_length=100)
    index = models.IntegerField(default=1)

    def __str__(self):
        return self.en_name




class Discount(models.Model):
    
    value = models.IntegerField()
    start_date = models.DateField()
    end_date = models.DateField()




class DateOff(models.Model):
    from_date = models.DateField()
    to_date = models.DateField()



    def __str__(self):
        return f'{self.from_date.strftime("%d-%m-%Y")} - {self.to_date.strftime("%d-%m-%Y")}'

    def get_absolute_url(self):
        return reverse("dashboard:set-date-off")

class Visit(models.Model):
    date = models.DateTimeField(auto_now_add=True)

class SubscribedUser(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

class DeliveryDate(models.Model):
    en_date = models.CharField(max_length=50)
    ar_date = models.CharField(max_length=50)
    number = models.IntegerField(default=0)

    def __str__(self):
        return self.en_date


class Choice(models.Model):
    en_choice = models.CharField(max_length=200, unique=True)
    ar_choice = models.CharField(max_length=200, unique=True)

    
    def __str__(self):
        return self.en_choice

    def get_absolute_url(self):
        return reverse("dashboard:items")



class DeliveryCharge(models.Model):
    price = models.IntegerField()


class ContactUs(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)


class BannerImage(models.Model):
    image1 = CloudinaryField("image1", blank=True, null=True)
    image2 = CloudinaryField("image2", blank=True, null=True)
    image3 = CloudinaryField("image3", blank=True, null=True)
    image4 = CloudinaryField("image4", blank=True, null=True)
    image5 = CloudinaryField("image5", blank=True, null=True)
    picture1 = CloudinaryField("picture1", blank=True, null=True)
    picture2 = CloudinaryField("picture2", blank=True, null=True)
    picture3 = CloudinaryField("picture3", blank=True, null=True)
    picture4 = CloudinaryField("picture4", blank=True, null=True)
    picture5 = CloudinaryField("picture5", blank=True, null=True)

class ItemChoice(models.Model):
    choice = models.CharField(max_length=500)



class Card(models.Model):
    en_name = models.CharField(max_length=100)
    ar_name = models.CharField(max_length=100, blank=True, null=True)
    image = CloudinaryField("image", blank=True, null=True)
    picture = CloudinaryField("picture", blank=True, null=True)
    
    price = models.DecimalField(max_digits=6, decimal_places=3)
    slug = models.SlugField(blank=True, null=True)


    def __str__(self):
        return self.en_name


    def save(self, *args, **kwargs):
        self.slug = slugify(self.en_name)
        super(Card, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("dashboard:cards")

class Ribbon(models.Model):
    en_name = models.CharField(max_length=100)
    ar_name = models.CharField(max_length=100, blank=True, null=True)
    image = CloudinaryField("image", blank=True, null=True)
    picture = CloudinaryField("picture", blank=True, null=True)

    price = models.DecimalField(max_digits=6, decimal_places=3)
    slug = models.SlugField(blank=True, null=True)


    def __str__(self):
        return self.en_name


    def save(self, *args, **kwargs):
        self.slug = slugify(self.en_name)
        super(Ribbon, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("dashboard:ribbons")


class Flower(models.Model):
    en_name = models.CharField(max_length=100)
    ar_name = models.CharField(max_length=100, blank=True, null=True)
    image = CloudinaryField("image", blank=True, null=True)
    picture = CloudinaryField("picture", blank=True, null=True)

    price = models.DecimalField(max_digits=6, decimal_places=3)
    slug = models.SlugField(blank=True, null=True)

    def __str__(self):
        return self.en_name


    def save(self, *args, **kwargs):
        self.slug = slugify(self.en_name)
        super(Flower, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("dashboard:flowers")


class Topper(models.Model):
    en_name = models.CharField(max_length=100)
    ar_name = models.CharField(max_length=100, blank=True, null=True)
    image = CloudinaryField("image", blank=True, null=True)
    picture = CloudinaryField("picture", blank=True, null=True)

    price = models.DecimalField(max_digits=6, decimal_places=3)
    slug = models.SlugField(blank=True, null=True)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.en_name)
        super(Topper, self).save(*args, **kwargs)

    def __str__(self):
        return self.en_name

    def get_absolute_url(self):
        return reverse("dashboard:toppers")



class Tray(models.Model):
    en_name = models.CharField(max_length=100)
    ar_name = models.CharField(max_length=100, blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    image = CloudinaryField("image", blank=True, null=True)
    picture = CloudinaryField("picture", blank=True, null=True)

    height = models.DecimalField(max_digits=4, decimal_places=1, null=True, blank=True)
    width = models.DecimalField(max_digits=4, decimal_places=1, null=True, blank=True)
    length = models.DecimalField(max_digits=4, decimal_places=1, null=True, blank=True)
    diameter = models.DecimalField(max_digits=4, decimal_places=1, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=3)
    weight = models.DecimalField(max_digits=6, decimal_places=3)
    unit = models.CharField(choices=UNIT_CHOICE, default="Kilogram", max_length=50)
    ar_unit = models.CharField(choices=AR_UNIT_CHOICE, default="كجم", max_length=50)
    items = models.IntegerField(blank=True, null=True)
    type = models.CharField(choices=TRAY_CHOCOLATE_TYPE, max_length=100, default="Bars")
    delivery_date = models.ForeignKey(DeliveryDate, on_delete=models.SET_NULL, null=True, blank=True, default=1)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.en_name)
        super(Tray, self).save(*args, **kwargs)

    def __str__(self):
        return self.en_name

    def get_absolute_url(self):
        return reverse("dashboard:trays")





class MinimumOrder(models.Model):
    price = models.DecimalField(max_digits=6, decimal_places=3)

class Box(models.Model):
    name = models.CharField(max_length=100, default="box")
    image = CloudinaryField("image")
    picture = CloudinaryField("picture", blank=True, null=True)


    def __str__(self):
        return self.name

class ChocolateType(models.Model):
    title = models.CharField(max_length=100)
    image = CloudinaryField("image")
    picture = CloudinaryField("picture", blank=True, null=True)

    checked = models.BooleanField(default=False)

    def __str__(self):
        return self.title







class AboutUsMainImage(models.Model):
    image = models.ImageField(upload_to="images/about-us", validators=[validators.image_size])




class AboutUsContent(models.Model):
    main_text = models.TextField()
    ar_main_text = models.TextField(null=True, blank=True)

    ar_secondary_text = models.TextField(null=True, blank=True)
    secondary_text = models.TextField()


    image = CloudinaryField("image", null=True)


class AboutUsTopic(models.Model):
    title = models.CharField(max_length=100)
    ar_title = models.CharField(max_length=100, null=True, blank=True)

templates/add-category-item.html
<!DOCTYPE html>

<html lang="en-us" dir="ltr">
<head>
<title>category | Change category | Chocolate.co Admin</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">

  <link rel="stylesheet" type="text/css" href="/static/admin/css/nav_sidebar.css">
  <script src="/static/admin/js/nav_sidebar.js" defer></script>

<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">


<script src="/admin/jsi18n/"></script>
<script src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script src="/static/admin/js/jquery.init.js"></script>
<script src="/static/admin/js/core.js"></script>
<script src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script src="/static/admin/js/actions.js"></script>
<script src="/static/admin/js/urlify.js"></script>
<script src="/static/admin/js/prepopulate.js"></script>
<script src="/static/admin/js/vendor/xregexp/xregexp.js"></script>


    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
    

<meta name="robots" content="NONE,NOARCHIVE">
<style>

body {
    background: #fff
}

h1 {
    color: #000
}
</style>
</head>


<body class=" app-app model-category change-form"
  data-admin-utc-offset="0">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header" style="background-color: #a5705b; color: #fff">
        <div id="branding">
        
<h1 id="site-name"><a style="color: #fff" href="/admin/">Chocolate.co Admin</a></h1>

        </div>
        
        
        <div id="user-tools">
            
                Welcome,
                <strong>yazed</strong>.
            
            
                
                    <a href="/">View site</a> /
                
                
                    
                    
                
                
                <a href="/admin/password_change/">Change password</a> /
                
                <a href="/admin/logout/">Log out</a>
            
        </div>
        
        
        
    </div>
    <!-- END Header -->
    
<div class="breadcrumbs">
<a href="/admin/">Home</a>
&rsaquo; <a href="/admin/app/">App</a>
&rsaquo; <a href="/admin/app/category/">Categories</a>
&rsaquo; category
</div>

    

    <div class="main shifted" id="main">
      
        
          
<button style="margin-top: 5%;" class="sticky toggle-nav-sidebar" id="toggle-nav-sidebar" aria-label="Toggle navigation"></button>
<nav style="margin-top: 5%" class="sticky" id="nav-sidebar">
  


</style>

  
    <div class="app-app module current-app">
      <table>
        <caption style="background-color: #a5705b">
          <a href="/admin/app/" class="section" title="Models in the App application">App</a>
        </caption>
        
          <tr class="model-boximage">
            
              <th scope="row"><a style="color: #fff" href="/admin/app/boximage/">Box images</a></th>
            

            
              <td><a style="color: #fff" href="/admin/app/boximage/add/" class="addlink">Add</a></td>
            

            
          </tr>
        
          <tr class="model-boxitem">
            
              <th scope="row"><a style="color: #fff" href="/admin/app/boxitem/">Box items</a></th>
            

            
              <td><a style="color: #fff" href="/admin/app/boxitem/add/" class="addlink">Add</a></td>
            

            
          </tr>
        
          <tr class="model-category current-model">
            
              <th scope="row"><a style="color: #fff" href="/admin/app/category/" aria-current="page">Categories</a></th>
            

            
              <td><a style="color: #fff" href="/admin/app/category/add/" class="addlink">Add</a></td>
            

            
          </tr>
        
          <tr class="model-item">
            
              <th scope="row"><a style="color: #fff" href="/admin/app/item/">Items</a></th>
            

            
              <td><a style="color: #fff" href="/admin/app/item/add/" class="addlink">Add</a></td>
            

            
          </tr>
        
          <tr class="model-orderboxitem">
            
              <th scope="row"><a style="color: #fff" href="/admin/app/orderboxitem/">Order box items</a></th>
            

            
              <td><a style="color: #fff" href="/admin/app/orderboxitem/add/" class="addlink">Add</a></td>
            

            
          </tr>
        
          <tr class="model-orderitem">
            
              <th scope="row"><a style="color: #fff" href="/admin/app/orderitem/">Order items</a></th>
            

            
              <td><a style="color: #fff" href="/admin/app/orderitem/add/" class="addlink">Add</a></td>
            

            
          </tr>
        
          <tr class="model-order">
            
              <th scope="row"><a style="color: #fff" href="/admin/app/order/">Orders</a></th>
            

            
              <td><a style="color: #fff" href="/admin/app/order/add/" class="addlink">Add</a></td>
            

            
          </tr>
        
          <tr class="model-profile">
            
              <th scope="row"><a style="color: #fff" href="/admin/app/profile/">Profiles</a></th>
            

            
              <td><a style="color: #fff" href="/admin/app/profile/add/" class="addlink">Add</a></td>
            

            
          </tr>
        
      </table>
    </div>
  
    <div class="app-auth module">
      <table>
        <caption style="background-color: #a5705b">
          <a href="/admin/auth/" class="section" title="Models in the Authentication and Authorization application">Authentication and Authorization</a>
        </caption>
        
          <tr class="model-group">
            
              <th scope="row"><a style="color: #fff" href="/admin/auth/group/">Groups</a></th>
            

            
              <td><a style="color: #fff" href="/admin/auth/group/add/" class="addlink">Add</a></td>
            

            
          </tr>
        
          <tr class="model-user">
            
              <th scope="row"><a style="color: #fff" href="/admin/auth/user/">Users</a></th>
            

            
              <td><a style="color: #fff" href="/admin/auth/user/add/" class="addlink">Add</a></td>
            

            
          </tr>
        
      </table>
    </div>
  


</nav>

        
      
      <div class="content">
        
          
        
        <!-- Content -->
        <div id="content" class="colM">
          
          <h1>Change category</h1>
          <h2>category</h2>
          <div id="content-main">


  <ul class="object-tools">
    
      

<li>
    
    <a href="/admin/app/category/1/history/" class="historylink">History</a>
</li>



    
  </ul>


<form method="post" id="category_form" enctype='multipart/form-data' novalidate>
{% csrf_token %}
<div>







<fieldset class="module aligned ">

  
  
  <div class="form-row field-title">
    <div>
      <label class="required" for="id_title">Title:</label>
      {{ form.title }}  
    </div>
      
  </div>


  <div class="form-row field-title">
    <div>
      <label class="required" for="id_title">Image:</label>
      {{ form.picture }}  
    </div>
      
  </div>


  <div class="form-row field-title">
    <div>
      <label class="required" for="id_title">Description:</label>
      {{ form.description }}  
    </div>
      
  </div>



  <div class="form-row field-title">
    <div>
      <label class="required" for="id_title">Price:</label>
      {{ form.price }}  
    </div>
      
  </div>


  <div class="form-row field-title">
    <div>
      <label class="required" for="id_title">Slug:</label>
      {{ form.slug }}  
    </div>
      
  </div>


  
</fieldset>













<div class="submit-row">

<input type="submit" value="Save" class="default" name="_save">

    
    <p class="deletelink-box"><a href="/admin/app/category/1/delete/" class="deletelink">Delete</a></p>


<input type="submit" value="Save and add another" name="_addanother">
<input type="submit" value="Save and continue editing" name="_continue">


</div>



    <script id="django-admin-form-add-constants"
            src="/static/admin/js/change_form.js"
            
            async>
    </script>




<script id="django-admin-prepopulated-fields-constants"
        src="/static/admin/js/prepopulate_init.js"
        data-prepopulated-fields="[]">
</script>


</div>
</form></div>

          
          <br class="clear">
        </div>
        <!-- END Content -->
        <div id="footer"></div>
      </div>
    </div>
</div>
<!-- END Container -->
</body>
</html>

templates/checkout_loading.html
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Chocolate.co - Checkout Done</title>
    <link rel="stylesheet" href="{% static 'css/style-skin-food02.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>\
    <script>
      !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
      n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
      n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
      t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
      document,'script','https://connect.facebook.net/en_US/fbevents.js');
      
      fbq('init', '3179941832325793');
      fbq('track', 'Purchase', {
        value: {{ order.get_discount_total }},
        currency: 'KWD'
      });
      
    </script>
    <noscript>
      <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=3179941832325793&ev=PageView&noscript=1"/>
    </noscript>

    <!-- Snap Pixel Code -->
    <script type='text/javascript'>
      (function(e,t,n){if(e.snaptr)return;var a=e.snaptr=function()
      {a.handleRequest?a.handleRequest.apply(a,arguments):a.queue.push(arguments)};
      a.queue=[];var s='script';r=t.createElement(s);r.async=!0;
      r.src=n;var u=t.getElementsByTagName(s)[0];
      u.parentNode.insertBefore(r,u);})(window,document,
      'https://sc-static.net/scevent.min.js');
      snaptr('init', '45774274-ef6a-4a6f-ad1b-9f1ee1efafac', {
      'user_email': '__INSERT_USER_EMAIL__'
      });
      snaptr('track', 'PURCHASE', { 'currency': 'KWD', 'price': {{ order.get_discount_total }} });
    </script>
    <!-- End Snap Pixel Code -->
  </head>
  <body>
    <div id="loader-wrapper">
      <div id="loader">
        <div class="dot"></div>
        <div class="dot"></div>
        <div class="dot"></div>
        <div class="dot"></div>
        <div class="dot"></div>
        <div class="dot"></div>
        <div class="dot"></div>
      </div>
    </div>
  </body>
  <script>
    var wsStart = "ws://";
    if (location.protocol == "https:") {
      wsStart = "wss://";
    }
    var endpoint = wsStart + location.host + "/dashboard/orders/";
    console.log(endpoint);

    var socket = new WebSocket(endpoint);

    socket.onopen = function (e) {
      console.log("open", e);
      socket.send("{{ request.user }}");
    };
    socket.onmessage = function (e) {
      var data = JSON.parse(e.data);
      console.log(data.status);
      document.location.href = "/socket-checkout";
    };
    socket.onerror = function (e) {
      console.log("error", e);
    };
    socket.onclose = function (e) {
      console.log("close", e);
    };
  </script>
</html>