app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='home'),
    

    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
    path('add-to-cart/<id>', views.add_to_cart, name="add"),
    path('add-to-cart-detail/<id>', views.add_to_cart_detail, name="add-detail"),

    path('remove-from-cart/<id>', views.remove_from_cart, name="remove"),
    path('product/<id>', views.detail_view, name="detail"),
    path('item-occasions', views.occasions_list, name="occasions"),
    path("customize-your-box", views.chocolate_type, name="chocolate_type"),
    # path("customize-your-box/chocolate-weight", views.chocolate_weight, name="chocolate_weight"),
    # path("customize-your-box/chocolate-box", views.chocolate_box, name="chocolate_box"),
    # path("customize-your-box/box-items", views.box_items_choice, name="box-items-choice"),
    path("customize-your-box/box-items-post", views.box_items_choice_post, name="box-items-choice-post"),
    # path('customize-your-box/done', views.custom_box_done, name="box-done"),
    path('cart', views.cart, name="cart"),
    path('add-quantity/<slug>', views.add_quantity, name="add-quantity"),
    path('remove-quantity/<id>', views.remove_quantity, name="remove-quantity"),
    path('checkout', views.CheckoutView.as_view(), name='checkout'),
    path('checkout-post', views.checkout, name='checkout-post'),
    path('clear-cart', views.clear_cart, name="clear-cart"),
    path('account/<pk>', views.Account.as_view(), name="account"),
    path('about-us', views.about_us, name="about-us"),
    path("ajax-add/<id>", views.ajax_add, name="ajax-add"),
    path("add-box-quantity/<slug>", views.add_box_quantity, name="add-box-quantity"),
    path("remove-box-quantity/<id>", views.remove_box_quantity, name="remove-box-quantity"),
    path("remove-box-from-cart/<id>", views.remove_box_from_cart, name="remove-box-from-cart"),
    path("add-checkout/<id>", views.add_check, name="add-check"),
    path("remove-checkout/<slug>", views.remove_check, name="remove-check"),
    path("add-box-checkout/<slug>", views.add_box_quantity_check, name="add-box-check"),
    path("remove-box-checkout/<slug>", views.remove_box_check, name="remove-box-check"),
    path("operation", views.operation, name="op-index"),
    path("operation/login", views.operation_login, name="op-login"),
    path("operation/order_details/<id>", views.order_details, name="op-order-details"),
    path("socket-checkout", views.socket_checkout, name="socket-checkout"),
    path("checkout-done", views.checkout_done, name="checkout-done"),
    path("verify-email", views.email_verification, name="check-pin"),
    path("send-payment", views.send_payment, name="send-payment"),
    path("ar-send-payment", views.ar_send_payment, name="ar-send-payment"),

    path("add-favorite/<id>", views.add_favorite, name="add-favorite"),
    path("remove-favorite/<id>", views.remove_favorite, name="remove-favorite"),
    path("add-favorite-detail/<id>", views.add_favorite_detail, name="add-favorite-detail"),
    path("remove-favorite-detail/<id>", views.remove_favorite_detail, name="remove-favorite-detail"),
    path("search-results", views.search, name="search"),
    path("favorites", views.favorites, name="favorites"),
    path("category-items/<id>", views.categories_home, name="category-items"),
    path("forgot-password", views.forgot_password, name="forgot-password"),
    path("reset-password", views.reset_password, name="reset-password"),
    path("change-password", views.change_password, name="change-password"),
    path("orders-history", views.orders_history, name="orders-history"),
    path("visitor", views.visitor, name="visitor"),
    path("terms-conditions", views.terms_and_conditions, name="terms-conditions"),
    path("privacy-policy", views.privacy_policy, name="privacy-policy"),
    path("add-visits", views.add_visits, name="add-visits"),
    path("checkout-failed", views.checkout_failed, name="checkout-failed"),


    path("submit-coupon", views.submit_coupon, name="submit-coupon"),
    path("replace-coupon", views.replace_coupon, name="replace-coupon"),


    path("ar-submit-coupon", views.ar_submit_coupon, name="ar-submit-coupon"),
    path("ar-replace-coupon", views.ar_replace_coupon, name="ar-replace-coupon"),






    path("create-visitor", views.create_visitor, name="create-visitor"),

    path("order-summary", views.order_summary, name="order-summary"),



    path("subscribe", views.subscribe, name="subscribe"),
    path("contact-us", views.contact_us_post, name="contact-us"),


    



    path("send-conf-email", views.send_confirmatiion_email),

    




    







    path('ar/', views.ar_index, name='ar-home'),
    path('ar/category-items/<id>', views.ar_categories_home, name='ar-category-items'),
    path('ar/product/<id>', views.ar_detail_view, name='ar-detail'),
    path("ar/customize-your-box", views.ar_chocolate_type, name="ar_chocolate_type"),
    path("ar/about-us", views.ar_about_us, name="ar-about-us"),
    path("ar/register", views.ar_register, name="ar-register"),
    path("ar/login", views.ar_user_login, name="ar-login"),
    path("ar/logout", views.ar_user_logout, name="ar-logout"),
    path("ar/cart", views.ar_cart, name="ar-cart"),
    path('ar/checkout', views.ArCheckoutView.as_view(), name='ar-checkout'),
    path('ar/account/<pk>', views.ArAccount.as_view(), name='ar-account'),
    path('ar/change-password', views.ar_change_password, name='ar-change-password'),
    path('ar/reset-password', views.ar_reset_password, name='ar-reset-password'),
    path('ar/forgot-password', views.ar_forgot_password, name='ar-forgot-password'),


    path('ar/orders-history', views.ar_orders_history, name='ar-orders-history'),
    path('ar/favorites', views.ar_favorites, name='ar-favorites'),
    path("ar/search-results", views.ar_search, name="ar-search"),
    path('ar/checkout-post', views.ar_checkout, name='ar-checkout-post'),
    path("ar/visitor", views.ar_visitor, name="ar-visitor"),
    path("ar/checkout-done", views.ar_checkout_done, name="ar-checkout-done"),
    path("ar/socket-checkout", views.ar_socket_checkout, name="ar-socket-checkout"),
    path("ar/terms-conditions", views.ar_terms_and_conditions, name="ar-terms-conditions"),
    path("ar/order-summary", views.ar_order_summary, name="ar-order-summary"),
    path("ar/privacy-policy", views.ar_privacy_policy, name="ar-privacy-policy"),
    path("ar-remove-box-from-cart/<id>", views.ar_remove_box_from_cart, name="ar-remove-box-from-cart"),
    path("ar/verify-email", views.ar_email_verification, name="ar-check-pin"),
    path("ar/checkout-failed", views.ar_checkout_failed, name="ar-checkout-failed"),
    path("ar/create-visitor", views.ar_create_visitor, name="ar-create-visitor"),




    path("images", views.images)














    
    










]


# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chocolate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path("dashboard/", include("dashboard.urls")),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.index, name="index"),
    path("items/", views.items_view, name="items"),
    path("create-item/", views.CreateItem.as_view(), name="create-item"),
    path("update/<pk>/", views.UpdateItem.as_view(), name="update-item"),
    path("delete/<id>/", views.delete_item, name="delete-item"),
    path("categories/", views.categories_view, name="categories"),
    path("create-category/", views.create_category, name="create-category"),
    path("update-category/<id>", views.update_category, name="update-category"),
    path("delete-category/<id>", views.delete_category, name="delete-category"),

    path('create-subcategory-item/<id>', views.create_subcategory_item, name="create-subcategory-item"),
    path('create-category-item/<id>', views.create_category_item, name="create-category-item"),

    path("orders/", views.orders, name="orders"),
    path("change-status/<id>/<str:status>", views.change_status, name="change-status"),
    path("change-new-status/<id>/<str:status>", views.change_new_status, name="change-new-status"),
    path("cancel-order/<id>", views.cancel_order, name="cancel-order"),


    path("working-hours/<pk>", views.WorkingHours.as_view(), name="working-hours"),
    path("days-list", views.days_list, name="days-list"),
    path("order/<id>", views.order_details, name="order-details"),



    path("about-us", views.about_us, name="about-us"),
    path("about-us/topics", views.topics_list, name="about-topics"),
    path("about-us/content", views.UpdateAboutContent.as_view(), name="about-us-content"),
    path("about-us/main-image", views.UpdateMainImage.as_view(), name="about-main-image"),
    path("about-us/update-topic/<pk>", views.UpdateTopic.as_view(), name="update-topic"),

   



    path("customized-box", views.customized_box, name="customized-box"),
    path("customized-box/create-type", views.AddType.as_view(), name="add-type"),
    path("customized-box/update-type/<pk>", views.UpdateType.as_view(), name="update-type"),
    path("customized-box/types", views.types, name="types"),
    path("customized-box/create-box", views.AddBox.as_view(), name="add-box"),
    path("customized-box/update-box/<pk>", views.UpdateBox.as_view(), name="update-box"),
    path("customized-box/boxes", views.boxes, name="boxes"),


    path("login", views.dash_login, name="dash-login"),
    path("logout", views.dash_logout, name="dash-logout"),




    path("customers", views.customers, name="customers"),
    path("transactions", views.transactions, name="transactions"),
    path("invoice/<order_id>", views.invoice, name="invoice"),

    path("create-subcategory/<category_id>", views.create_subcategory, name="create-sub"),
    path("update-subcategory/<pk>", views.UpdateSubCategory.as_view(), name="update-sub"),


    path("delete-sub/<id>", views.delete_sub, name="delete-sub"),


    path("trays/", views.trays_view, name="trays"),
    path("add-tray/", views.AddTray.as_view(), name="add-tray"),
    path("delete-tray/<id>", views.delete_tray, name="delete-tray"),
    path("update-tray/<slug>", views.UpdateTray.as_view(), name="update-tray"),



    path("flowers/", views.flowers_view, name="flowers"),
    path("add-flower/", views.AddFlower.as_view(), name="add-flower"),
    path("delete-flower/<id>", views.delete_flower, name="delete-flower"),
    path("update-flower/<slug>", views.UpdateFlower.as_view(), name="update-flower"),



    path("ribbons/", views.ribbons_view, name="ribbons"),
    path("add-ribbon/", views.AddRibbon.as_view(), name="add-ribbon"),
    path("delete-ribbon/<id>", views.delete_ribbon, name="delete-ribbon"),
    path("update-ribbon/<slug>", views.UpdateRibbon.as_view(), name="update-ribbon"),


    path("toppers/", views.toppers_view, name="toppers"),
    path("add-topper/", views.AddTopper.as_view(), name="add-topper"),
    path("delete-topper/<id>", views.delete_topper, name="delete-topper"),
    path("update-topper/<slug>", views.UpdateTopper.as_view(), name="update-topper"),


    path("cards/", views.cards_view, name="cards"),
    path("add-card/", views.AddCard.as_view(), name="add-card"),
    path("delete-card/<id>", views.delete_card, name="delete-card"),
    path("update-card/<slug>", views.UpdateCard.as_view(), name="update-card"),



    path("box-items/", views.box_items_view, name="box-items"),
    path("add-box-item/", views.CreateBoxItem.as_view(), name="add-box-item"),
    path("update-box-item/<pk>", views.UpdateBoxItem.as_view(), name="update-box-item"),
    path("delete-box-item/<id>", views.delete_box_item, name="delete-box-item"),


    path("update-banner/", views.UpdateBannerImage.as_view(), name="update-banner"),








    path("update-minimum-order", views.UpdateMinimuOrder.as_view(), name="update-minimum-order"),
    path("update-delivery-charge", views.UpdateDeliveryCharge.as_view(), name="update-delivery-charge"),


    path("contact-us", views.contact_us_messages, name="contact-messages"),
    path("contact-us/<id>", views.contact_us_message, name="contact-message"),

    path("create-choice", views.CreateChoice.as_view(), name="create-choice"),


    path("add-package", views.AddPackage.as_view(), name="add-package"),
    path("update-package/<pk>", views.UpdatePackage.as_view(), name="update-package"),
    path("delete-package/<id>", views.delete_package, name="delete-package"),


    path("packages", views.packages_view, name="packages"),



    path("reports", views.reports, name="reports"),




    
    path("general-income-report", views.general_income_report, name="general-income"),
    path("advanced-income-report", views.advanced_income_report, name="advanced-income"),
    path("visits-report", views.visits_report, name="visits-report"),
    path("users-report", views.users_report, name="users-report"),


    path("set-date-off", views.set_date_off, name="set-date-off"),
    path("update-date-off/<id>", views.update_date_off, name="update-date-off"),
    path("delete-date-off/<id>", views.delete_date_off, name="delete-date-off"),


    path("off-dates", views.off_dates, name="off-dates"),
    path("update-pop-up", views.UpdatePopUp.as_view(), name="update-pop-up"),




    path("create-coupon", views.CreateCoupon.as_view(), name="create-coupon"),
    path("update-coupon/<pk>", views.UpdateCoupon.as_view(), name="update-coupon"),
    path("update-discount", views.UpdateDiscount.as_view(), name="update-discount"),


    path("coupons-list", views.coupons_list, name="coupons-list"),
    path("delete-coupon/<id>", views.delete_coupon, name="delete-coupon"),

    path("colors", views.colors_list, name="colors-list"),
    path("create-color", views.CreateColor.as_view(), name="create-color"),
    path("update-color/<pk>", views.UpdateColor.as_view(), name="update-color"),
    path("delete-color/<pk>", views.delete_color, name="delete-color"),


    path("flavors", views.flavors_list, name="flavors-list"),
    path("create-flavor", views.CreateFlavor.as_view(), name="create-flavor"),
    path("update-flavor/<pk>", views.UpdateFlavor.as_view(), name="update-flavor"),
    path("delete-flavor/<pk>", views.delete_flavor, name="delete-flavor"),













]

dashboard/models.py
from django.db import models

# Create your models here.

templates/dashboard/colors_list.html
{% extends 'dashboard/base.html' %}


{% block content %}

<div class="content-body">
    <div class="container-fluid">
        
        <div>
            <div class="page-titles" style="text-align: right; margin-bottom: 0">
                <a class="col-xl-3 col-lg-4 col-md-4 col-6" href="{% url 'dashboard:create-color' %}"><button style="padding: 0;" class="d-inline-block form-control date-button btn btn-primary light btn-rounded">Add Color</button></a>
            </div>
            <div class="card">
                <div class="card-header d-sm-flex flex-wrap d-block pb-0 border-0">
                    Colors
                </div>
                <div class="card-body">
                   
                    <div class="row align-items-center">	
                        <div class="table-responsive">
                            <table class="table table-responsive-lg mb-0 table-striped">
                                
                                <tbody id="colors">
                                    {% for color in colors|dictsort:"index" %}
                                        <tr class="btn-reveal-trigger color-{{ color.id }}">
                                            
                                            <td class="py-2">{{ color.en_name }}</td>

                                            <td class="py-2">{{ color.ar_name }}</td>


                                            
                                            
                                            <td style="text-align: right" >
                                                <span style="text-align: right"><a href="{% url 'dashboard:update-color' color.id %}"><i style="color: #00205C" class="fa fa-pencil"></i></a></span>
                                                <span style="text-align: right; margin-left: 15px"><a href="{% url 'dashboard:delete-color' color.id %}"><i style="color: #dc3545" class="fa fa-trash"></i></a></span>

                                            </td>
                                            
                                            
                                        </tr>
                                        
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                            
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/dashboard/customized_box.html
{% extends 'dashboard/base.html' %} {% block content %}

<div class="content-body">
  <div
    class="container-fluid"
    style="
      text-align: center;
      display: flex;
      flex-direction: column;
      align-items: center;
    "
  >
    
  <a href={% url 'dashboard:types'  %} box="button" class="btn btn-outline-primary" style="margin: 10px 0; width: 190px">Types</a>
  <a href={% url 'dashboard:boxes'  %} box="button" class="btn btn-outline-primary" style="margin: 10px 0; width: 190px">Boxes</a>

  </div>
</div>

{% endblock content %}

templates/dashboard/flavors_list.html
{% extends 'dashboard/base.html' %}


{% block content %}

<div class="content-body">
    <div class="container-fluid">
        
        <div>
            <div class="page-titles" style="text-align: right; margin-bottom: 0">
                <a class="col-xl-3 col-lg-4 col-md-4 col-6" href="{% url 'dashboard:create-flavor' %}"><button style="padding: 0;" class="d-inline-block form-control date-button btn btn-primary light btn-rounded">Add Flavor</button></a>
            </div>
            <div class="card">
                <div class="card-header d-sm-flex flex-wrap d-block pb-0 border-0">
                    Flavors
                </div>
                <div class="card-body">
                   
                    <div class="row align-items-center">	
                        <div class="table-responsive">
                            <table class="table table-responsive-lg mb-0 table-striped">
                                
                                <tbody id="flavors">
                                    {% for flavor in flavors|dictsort:"index" %}
                                        <tr class="btn-reveal-trigger flavor-{{ flavor.id }}">
                                            
                                            <td class="py-2">{{ flavor.en_name }}</td>

                                            <td class="py-2">{{ flavor.ar_name }}</td>


                                            
                                            
                                            <td style="text-align: right" >
                                                <span style="text-align: right"><a href="{% url 'dashboard:update-flavor' flavor.id %}"><i style="color: #00205C" class="fa fa-pencil"></i></a></span>
                                                <span style="text-align: right; margin-left: 15px"><a href="{% url 'dashboard:delete-flavor' flavor.id %}"><i style="color: #dc3545" class="fa fa-trash"></i></a></span>

                                            </td>
                                            
                                            
                                        </tr>
                                        
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                            
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/dashboard/items.html
{% extends 'dashboard/base.html' %}



{% block content %}

<div class="content-body">
    <div class="container-fluid">
        <!-- Add Order -->
        <div class="modal fade" id="addOrderModalside">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Add Menus</h5>
                        <button type="button" class="close" data-dismiss="modal"><span>&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form>
                            <div class="form-group">
                                <label class="text-black font-w500">Food Name</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label class="text-black font-w500">Order Date</label>
                                <input type="date" class="form-control">
                            </div>
                            <div class="form-group">
                                <label class="text-black font-w500">Food Price</label>
                                <input type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <button type="button" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="page-titles" style="text-align: right;">
            <a class="col-xl-3 col-lg-4 col-md-4 col-6" href="{% url 'dashboard:create-category' %}"><button style="padding: 0;" class="d-inline-block form-control date-button btn btn-primary light btn-rounded">Add Category</button></a>
        </div>
        {% for category in categories %}
            <div style="background: #e5e5e5; padding: 60px; border-radius: 1.25rem; margin-bottom: 5%">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px;">
                    <div>
                        <h3>{{ category.en_title }}</h3>
                    </div>
                    <div class="row" style="text-align: right; justify-content: space-evenly;">
                        
                        <a class="col-xl-3 col-lg-4 col-md-4 col-12" href="{% url 'dashboard:create-sub' category.id %}"><button style="margin: 10px 0;" class="d-inline-block form-control date-button btn btn-primary light btn-rounded">Add Sub</button></a>

                        <a class="col-xl-3 col-lg-4 col-md-4 col-12" href="{% url 'dashboard:update-category' category.id %}"><button style="padding: 0; margin: 10px 0;" class="d-inline-block form-control date-button btn btn-primary light btn-rounded">Edit Category</button></a>
                        <a class="col-xl-3 col-lg-4 col-md-4 col-12" href="{% url 'dashboard:delete-category' category.id %}"><button style="padding: 0; margin: 10px 0;" class="d-inline-block form-control date-button btn btn-primary light btn-rounded">Delete Category</button></a>
                        <a class="col-xl-3 col-lg-4 col-md-4 col-12" href="{% url 'dashboard:create-category-item' category.id %}"><button style="padding: 0; margin: 10px 0;" class="d-inline-block form-control date-button btn btn-primary light btn-rounded">Add Item</button></a>

                    </div>
                
                </div>
                {% if category.subs.all.count > 0 %}
                    {% for sub in category.subs.all|dictsort:"number" %}
                        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px;">
                            <div>
                                <h3>{{ sub.en_title }}</h3>
                            </div>
                            <div class="row" style="text-align: right; justify-content: space-evenly;">
                                <a class="col-xl-3 col-lg-4 col-md-4 col-12" href="{% url 'dashboard:create-subcategory-item' sub.id %}"><button style="margin: 10px 0;" class="d-inline-block form-control date-button btn btn-primary light btn-rounded">Add Item</button></a>
                                <a class="col-xl-3 col-lg-4 col-md-4 col-12" href="{% url 'dashboard:update-sub' sub.id %}"><button style="margin: 10px 0;" class="d-inline-block form-control date-button btn btn-primary light btn-rounded">Edit Sub</button></a>
                                <a class="col-xl-3 col-lg-4 col-md-4 col-12" href="{% url 'dashboard:delete-sub' sub.id %}"><button style="margin: 10px 0;" class="d-inline-block form-control date-button btn btn-primary light btn-rounded">Delete Sub</button></a>

                            </div>
                        </div>
                        <div class="row" style="margin-bottom: 30px">
                        
                            
                            
                            {% for item in sub.items.all %}
                                {% if not item.customized_box and not item.is_deleted %}
                                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-xs-12 col-12">
                                        <div class="card">
                                            <div class="card-body">
                                                <div class="new-arrival-product">
                                                    <a href="{% url 'dashboard:update-item' item.id %}">
                                                        <div class="new-arrivals-img-contnent">
                                                            <img class="img-fluid" src="{{ item.picture.url }}" alt="">
                                                        </div>
                                                    </a>
                                                    <div class="new-arrival-content text-center mt-3">
                                                        <a href="{% url 'dashboard:update-item' item.id %}">
                                                            <h4>{{ item.title }}</h4>
                                                        </a>
                        
                        
                                                        <span class="price">{{ item.price }} KD</span>
                                                        <span style="display:block; text-align: right"><a href="{% url 'dashboard:delete-item' item.id %}"><i style="color: #dc3545" class="fa fa-trash"></i></a></span>
                        
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                        
                            {% endfor %}
                    
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="row" style="margin-bottom: 30px">
                        {% for item in category.items.all %}
                            {% if not item.customized_box and not item.is_deleted %}
                                
                                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-xs-12 col-12">
                                        <div class="card">
                                            <div class="card-body">
                                                <div class="new-arrival-product">
                                                    <a href="{% url 'dashboard:update-item' item.id %}">
                                                        <div class="new-arrivals-img-contnent">
                                                            <img class="img-fluid" src="{{ item.picture.url }}" alt="">
                                                        </div>
                                                    </a>
                                                    <div class="new-arrival-content text-center mt-3">
                                                        <a href="{% url 'dashboard:update-item' item.id %}">
                                                            <h4>{{ item.title }}</h4>
                                                        </a>
                        
                        
                                                        <span class="price">{{ item.price }} KD</span>
                                                        <span style="display:block; text-align: right"><a href="{% url 'dashboard:delete-item' item.id %}"><i style="color: #dc3545" class="fa fa-trash"></i></a></span>
                        
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                
                            {% endif %}
                    
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}